version: '3'

services:
  concourse-db:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://${myip}:8080
      CONCOURSE_ADD_LOCAL_USER: scooby:doo
      CONCOURSE_MAIN_TEAM_LOCAL_USER: scooby
  sonar:
    image: sonarqube
    privileged: true
    depends_on: [concourse-db]
    ports: ["9000:9000"]
    environment:
      sonar.jdbc.username: concourse_user
      sonar.jdbc.password: concourse_pass
      sonar.jdbc.url: jdbc:postgresql://${myip}/sonar
